image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

Bintray and GitHub Release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy
    - docker build -t bugaudit-runner .
  only:
    - master

#Pushing to DockerHub:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS clean install
#    - docker build -t bugaudit-runner .
#  only:
#    - master
