image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

stages:
  - "Build"
  - "Release"
  - "Triggers"

BugAudit CLI JAR Build:
  image: maven:3-jdk-8
  stage: "Build"
  script: mvn $MAVEN_CLI_OPTS clean deploy
  artifacts:
    expire_in: 1 hour
    paths:
      - target/bugaudit-runner.jar

BugAudit Environment Build:
  stage: "Release"
  script:
    - sh docker-builder
  only:
    - master

BugAudit Runner Build:
  stage: "Triggers"
  trigger: bugaudit/bugaudit
  only:
    - master