image: docker:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - package

Maven Build:
  image: maven:3-jdk-8
  stage: build
  script: mvn $MAVEN_CLI_OPTS clean deploy
  artifacts:
    paths:
      - target/bugaudit-runner.jar
      - bugaudit-runner

Publishing Docker Image:
  stage: deploy
  script:
    - sh docker-builder
  only:
    - master