image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

Deploying to Bintray:
  stage: deploy
  script:
    - sh build-dependency.sh shibme/freshrelease-api
    - mvn $MAVEN_CLI_OPTS clean deploy
  only:
    - master
