image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - "Maven Build"
  - "Docker Build"
  - "Downstream Triggers"

BugAudit CLI JAR Build:
  image: maven:3-jdk-8
  stage: "Maven Build"
  script: mvn $MAVEN_CLI_OPTS clean deploy
  artifacts:
    paths:
      - target/bugaudit-runner.jar
      - bugaudit-runner
      - bugaudit-command

BugAudit Environment Build:
  stage: "Docker Build"
  script:
    - sh docker-builder
  only:
    - master

BugAudit Runner Build:
  stage: "Downstream Triggers"
  trigger: bugaudit/bugaudit
  only:
    - master