image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - "Maven Build"
  - "BugAudit Platform Build"
  - "BugAudit Runner Build"

Executable JAR Builder:
  image: maven:3-jdk-8
  stage: "Maven Build"
  script: mvn $MAVEN_CLI_OPTS clean deploy
  artifacts:
    paths:
      - target/bugaudit-runner.jar
      - bugaudit-runner
      - bugaudit-command

BugAudit Platform Docker Image Builder:
  stage: "BugAudit Platform Build"
  script:
    - sh docker-builder
  only:
    - master

BugAudit Runner Build Trigger:
  stage: "BugAudit Runner Build"
  trigger: bugaudit/bugaudit