#!/usr/bin/env bash
if [ ! -z "$GIT_REPO" ]; then
    if [[ $GIT_REPO == http* ]]; then
        echo "Please provide a valid SSH based clone URI"
    else
        rm -rf bugaudit-scan-source
        git clone $GIT_REPO bugaudit-scan-source
        cd bugaudit-scan-source
        java -jar /bugaudit-workspace/bugaudit-runner.jar
    fi
else
    echo "Please set GIT_REPO environment variable"
fi
java -jar /bugaudit-workspace/bugaudit-runner.jar