#!/usr/bin/env bash
BUGAUDIT_VERSION="0.2"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build --build-arg BUGAUDIT_VERSION=$BUGAUDIT_VERSION -t bugaudit/bugaudit-env:$BUGAUDIT_VERSION .
docker tag bugaudit/bugaudit-env:$BUGAUDIT_VERSION bugaudit/bugaudit-env:latest
docker push bugaudit/bugaudit-env
docker logout