#!/usr/bin/env bash
DOCKER_VERSION_RESPONSE=$(docker -v)
EXPECTED_RESPONSE="Docker version "
if test "${DOCKER_VERSION_RESPONSE#*$EXPECTED_RESPONSE}" != "$DOCKER_VERSION_RESPONSE"
then
    export BUGAUDIT_HOST_WORKDIR=`pwd`
    if [ -z "$BUGAUDIT_SSH_PRIVATE_KEY" ]; then
        export BUGAUDIT_SSH_PRIVATE_KEY="$HOME/.ssh/id_rsa"
    fi
    if [[ $BUGAUDIT_CONFIG != http* ]]; then
        if [ -f "$BUGAUDIT_CONFIG" ]; then
            export BUGAUDIT_CONFIG_LOCAL_FILE="$BUGAUDIT_CONFIG"
        fi
    fi
    if [ -z "$BUGAUDIT_CONTAINER" ]; then
        export BUGAUDIT_CONTAINER="bugaudit-container"
        echo "BUGAUDIT_CONTAINER environment variable was not set."
        echo "Using default container name: $BUGAUDIT_CONTAINER"
    fi
    BUGAUDIT_CONTAINER=${BUGAUDIT_CONTAINER// /_}
    echo "Attempting to kill any running docker instances of BugAudit Runner:"
    docker kill $BUGAUDIT_CONTAINER
    echo "Attempting to remove any docker instances of BugAudit Runner:"
    docker rm $BUGAUDIT_CONTAINER
    docker pull bugaudit/bugaudit-runner
    echo "Running container: $BUGAUDIT_CONTAINER"
    docker run \
    -e BUGAUDIT_GIT_REPO \
    -e BUGAUDIT_GIT_BRANCH \
    -e BUGAUDIT_SSH_KEY_PASSPHRASE \
    -e BUGAUDIT_TRACKER_NAME \
    -e BUGAUDIT_TRACKER_ENDPOINT \
    -e BUGAUDIT_TRACKER_API_KEY \
    -e BUGAUDIT_TRACKER_USERNAME \
    -e BUGAUDIT_TRACKER_PASSWORD \
    -e BUGAUDIT_PROJECT \
    -e BUGAUDIT_ISSUETYPE \
    -e BUGAUDIT_CONFIG \
    -e BUGAUDIT_ASSIGNEE \
    -e BUGAUDIT_SCANNER_DIR \
    -e BUGAUDIT_TRACKER_READONLY \
    -e BUGAUDIT_SUBSCRIBERS \
    -e BUGAUDIT_SCANNER_CONFIG \
    -e BUGAUDIT_LANG \
    --name $BUGAUDIT_CONTAINER \
    -v $BUGAUDIT_HOST_WORKDIR:/bugaudit-host-dir \
    -v $BUGAUDIT_CONFIG_LOCAL_FILE:/bugaudit-config-dir/bugaudit-config.json \
    -v $BUGAUDIT_SSH_PRIVATE_KEY:/bugaudit-ssh-key/ssh-priv-key bugaudit/bugaudit-runner
else
    echo "Please install docker client before you begin."
fi