#!/usr/bin/env bash
DOCKER_VERSION_RESPONSE=$(docker -v)
EXPECTED_RESPONSE="Docker version "
if test "${DOCKER_VERSION_RESPONSE#*$EXPECTED_RESPONSE}" != "$DOCKER_VERSION_RESPONSE"
then
    docker kill bugaudit-runner
    docker rm bugaudit-runner
    docker run \
    -e BUGAUDIT_PROJECT \
    -e BUGAUDIT_ISSUETYPE \
    -e BUGAUDIT_TRACKER_NAME \
    -e BUGAUDIT_TRACKER_ENDPOINT \
    -e BUGAUDIT_TRACKER_API_KEY \
    -e BUGAUDIT_ASSIGNEE \
    -e BUGAUDIT_SCANNER_TOOL \
    -e BUGAUDIT_SCANNER_DIR \
    -e GIT_URL \
    -e GIT_AUTH_TOKEN \
    --name bugaudit-runner bugaudit/bugaudit-runner
else
    echo "Please install docker client before you begin."
fi