#!/bin/bash

#Set the environmental variables below before beginning
#export BUGAUDIT_CONFIG=bugaudit-config.json
#export BUGAUDIT_PROJECT=TEST
#export BUGAUDIT_ISSUETYPE=Bug
#export BUGAUDIT_ASSIGNEE=testuser@example.com
#export BUGAUDIT_SUBSCRIBERS=coolguy@test.com,tester@example.com
#export BUGAUDIT_LANG=Ruby
#export BUGAUDIT_TRACKER_READONLY=TRUE
#export BUGAUDIT_TRACKER_NAME=Jira
#export BUGAUDIT_TRACKER_ENDPOINT=https://example.jira.com
#export BUGAUDIT_TRACKER_USERNAME=user   #-- Not required if API Key is provided
#export BUGAUDIT_TRACKER_PASSWORD=password   #-- Not required if API Key is provided
#export BUGAUDIT_TRACKER_API_KEY=XxyYAbcZ   #-- Not required if username and password are provided
#export BUGAUDIT_SCANNER_PARSERONLY=TRUE
#export BUGAUDIT_SCANNER_TOOL=BundlerAudit
#export BUGAUDIT_SCANNER_DIR=test/code/path
#export BUGAUDIT_SCANNER_CONFIG=bugaudit-scanner-config.json
#export BUGAUDIT_SCANNER_BRAKEMAN_CONFIG="config/brakeman.yml"
#export BUGAUDIT_SCANNER_BRAKEMAN_IGNORE="config/brakeman.ignore"


if [ ! -z "$BUGAUDIT_SCANNER_DIR" ]; then
   cd $BUGAUDIT_SCANNER_DIR
fi

#Downloading jar from GitHub releases
curl -L https://github.com/bugaudit/bugaudit-cli/releases/download/0.2/bugaudit-cli-0.2.jar --output buaudit-cli.jar

java -jar buaudit-cli.jar